### PR TITLE
add resnet-50 prototxt

### PR DESCRIPTION
**Pull request by lixiang-ucas**
add support for Faster RCNN+ResNet-50.

### CODE REVIEW

**Comment by Eniac-Xie** [comment]
Thank you! 
Have you test the net on pascal voc? Would you please upload the resnet-50 you trained and give us the link?

**Comment by lixiang-ucas** [comment]
I have test the net on my own dataset (containing only one class), not  yet on pascal voc dataset.

**Comment by bq-li** [comment]
@Eniac-Xie .Thank you for your code. But I want to know how you train ResNet101_BN_SCALE_Merged.caffemodel which is used to initialize the model parameters。

**Comment by 646677064** [comment]
@lixiang-ucas thanks a lot.  @Eniac-Xie  I tried to change class-aware to class-agnotic(fg or bg, 2 class for bbox regression ) as R-FCN  did,but not save much memory (class=**6** ,RPN_POST_NMS_TOP_N=**1000**),and I trained  resnet-101 on my own dataset failed. I think the readonly brach take up much menory

**Pull request merged**
